version: "0.1"
services:
  postgres:
    container_name: postgres_cgm
    environment:
      HOSTNAME: ${CGM_POSTGRES_HOSTNAME}
      POSTGRES_DB: ${CGM_POSTGRES_DB}
      POSTGRES_PASSWORD: ${CGM_POSTGRES_PASSWORD}
      POSTGRES_USER: ${CGM_POSTGRES_USER}
    image: postgis/postgis:16-3.4
    ports:
      - ${CGM_POSTGRES_PORT}:5432
    restart: unless-stopped
